from pydantic import BaseModel, Field, ConfigDict, field_validator
from typing import Dict, Any

class ToolCallSpec(BaseModel):
    """Schema representing a single tool call generated by the LLM.

    - ``tool`` must be a non‑empty string identifying a registered tool.
    - ``parameters`` must be a dictionary (can be empty) containing the arguments.
    """

    tool: str = Field(..., min_length=1, description="Registered tool name")
    parameters: Dict[str, Any] = Field(default_factory=dict, description="Tool arguments")

    @field_validator("tool")
    @classmethod
    def tool_must_not_be_blank(cls, v: str) -> str:
        if not v.strip():
            raise ValueError("tool name must be a non‑empty string")
        return v

    model_config = ConfigDict(extra="forbid", json_schema_extra={
        "example": {
            "tool": "crm.read",
            "parameters": {"customer_id": "CUST-1001"}
        }
    })
